# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fla/projects/micromachine/sdk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fla/projects/micromachine/sdk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/fla/projects/micromachine/sdk && $(CMAKE_COMMAND) -E cmake_progress_start /home/fla/projects/micromachine/sdk/CMakeFiles /home/fla/projects/micromachine/sdk/runtime-abi/CMakeFiles/progress.marks
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f CMakeFiles/Makefile2 runtime-abi/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fla/projects/micromachine/sdk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f CMakeFiles/Makefile2 runtime-abi/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f CMakeFiles/Makefile2 runtime-abi/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f CMakeFiles/Makefile2 runtime-abi/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/fla/projects/micromachine/sdk && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
runtime-abi/CMakeFiles/libaeabi.dir/rule:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f CMakeFiles/Makefile2 runtime-abi/CMakeFiles/libaeabi.dir/rule
.PHONY : runtime-abi/CMakeFiles/libaeabi.dir/rule

# Convenience name for target.
libaeabi: runtime-abi/CMakeFiles/libaeabi.dir/rule

.PHONY : libaeabi

# fast build rule for target.
libaeabi/fast:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/build
.PHONY : libaeabi/fast

crt.obj: crt.S.obj

.PHONY : crt.obj

# target to build an object file
crt.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/crt.S.obj
.PHONY : crt.S.obj

crt.i: crt.S.i

.PHONY : crt.i

# target to preprocess a source file
crt.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/crt.S.i
.PHONY : crt.S.i

crt.s: crt.S.s

.PHONY : crt.s

# target to generate assembly for a file
crt.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/crt.S.s
.PHONY : crt.S.s

divdi3.obj: divdi3.S.obj

.PHONY : divdi3.obj

# target to build an object file
divdi3.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/divdi3.S.obj
.PHONY : divdi3.S.obj

divdi3.i: divdi3.S.i

.PHONY : divdi3.i

# target to preprocess a source file
divdi3.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/divdi3.S.i
.PHONY : divdi3.S.i

divdi3.s: divdi3.S.s

.PHONY : divdi3.s

# target to generate assembly for a file
divdi3.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/divdi3.S.s
.PHONY : divdi3.S.s

idiv.obj: idiv.S.obj

.PHONY : idiv.obj

# target to build an object file
idiv.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/idiv.S.obj
.PHONY : idiv.S.obj

idiv.i: idiv.S.i

.PHONY : idiv.i

# target to preprocess a source file
idiv.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/idiv.S.i
.PHONY : idiv.S.i

idiv.s: idiv.S.s

.PHONY : idiv.s

# target to generate assembly for a file
idiv.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/idiv.S.s
.PHONY : idiv.S.s

idivmod.obj: idivmod.S.obj

.PHONY : idivmod.obj

# target to build an object file
idivmod.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/idivmod.S.obj
.PHONY : idivmod.S.obj

idivmod.i: idivmod.S.i

.PHONY : idivmod.i

# target to preprocess a source file
idivmod.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/idivmod.S.i
.PHONY : idivmod.S.i

idivmod.s: idivmod.S.s

.PHONY : idivmod.s

# target to generate assembly for a file
idivmod.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/idivmod.S.s
.PHONY : idivmod.S.s

lasr.obj: lasr.S.obj

.PHONY : lasr.obj

# target to build an object file
lasr.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/lasr.S.obj
.PHONY : lasr.S.obj

lasr.i: lasr.S.i

.PHONY : lasr.i

# target to preprocess a source file
lasr.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/lasr.S.i
.PHONY : lasr.S.i

lasr.s: lasr.S.s

.PHONY : lasr.s

# target to generate assembly for a file
lasr.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/lasr.S.s
.PHONY : lasr.S.s

lcmp.obj: lcmp.S.obj

.PHONY : lcmp.obj

# target to build an object file
lcmp.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/lcmp.S.obj
.PHONY : lcmp.S.obj

lcmp.i: lcmp.S.i

.PHONY : lcmp.i

# target to preprocess a source file
lcmp.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/lcmp.S.i
.PHONY : lcmp.S.i

lcmp.s: lcmp.S.s

.PHONY : lcmp.s

# target to generate assembly for a file
lcmp.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/lcmp.S.s
.PHONY : lcmp.S.s

ldivmod.obj: ldivmod.S.obj

.PHONY : ldivmod.obj

# target to build an object file
ldivmod.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/ldivmod.S.obj
.PHONY : ldivmod.S.obj

ldivmod.i: ldivmod.S.i

.PHONY : ldivmod.i

# target to preprocess a source file
ldivmod.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/ldivmod.S.i
.PHONY : ldivmod.S.i

ldivmod.s: ldivmod.S.s

.PHONY : ldivmod.s

# target to generate assembly for a file
ldivmod.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/ldivmod.S.s
.PHONY : ldivmod.S.s

llsl.obj: llsl.S.obj

.PHONY : llsl.obj

# target to build an object file
llsl.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/llsl.S.obj
.PHONY : llsl.S.obj

llsl.i: llsl.S.i

.PHONY : llsl.i

# target to preprocess a source file
llsl.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/llsl.S.i
.PHONY : llsl.S.i

llsl.s: llsl.S.s

.PHONY : llsl.s

# target to generate assembly for a file
llsl.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/llsl.S.s
.PHONY : llsl.S.s

llsr.obj: llsr.S.obj

.PHONY : llsr.obj

# target to build an object file
llsr.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/llsr.S.obj
.PHONY : llsr.S.obj

llsr.i: llsr.S.i

.PHONY : llsr.i

# target to preprocess a source file
llsr.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/llsr.S.i
.PHONY : llsr.S.i

llsr.s: llsr.S.s

.PHONY : llsr.s

# target to generate assembly for a file
llsr.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/llsr.S.s
.PHONY : llsr.S.s

lmul.obj: lmul.S.obj

.PHONY : lmul.obj

# target to build an object file
lmul.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/lmul.S.obj
.PHONY : lmul.S.obj

lmul.i: lmul.S.i

.PHONY : lmul.i

# target to preprocess a source file
lmul.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/lmul.S.i
.PHONY : lmul.S.i

lmul.s: lmul.S.s

.PHONY : lmul.s

# target to generate assembly for a file
lmul.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/lmul.S.s
.PHONY : lmul.S.s

memmove.obj: memmove.S.obj

.PHONY : memmove.obj

# target to build an object file
memmove.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/memmove.S.obj
.PHONY : memmove.S.obj

memmove.i: memmove.S.i

.PHONY : memmove.i

# target to preprocess a source file
memmove.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/memmove.S.i
.PHONY : memmove.S.i

memmove.s: memmove.S.s

.PHONY : memmove.s

# target to generate assembly for a file
memmove.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/memmove.S.s
.PHONY : memmove.S.s

memset.obj: memset.S.obj

.PHONY : memset.obj

# target to build an object file
memset.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/memset.S.obj
.PHONY : memset.S.obj

memset.i: memset.S.i

.PHONY : memset.i

# target to preprocess a source file
memset.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/memset.S.i
.PHONY : memset.S.i

memset.s: memset.S.s

.PHONY : memset.s

# target to generate assembly for a file
memset.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/memset.S.s
.PHONY : memset.S.s

moddi3.obj: moddi3.S.obj

.PHONY : moddi3.obj

# target to build an object file
moddi3.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/moddi3.S.obj
.PHONY : moddi3.S.obj

moddi3.i: moddi3.S.i

.PHONY : moddi3.i

# target to preprocess a source file
moddi3.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/moddi3.S.i
.PHONY : moddi3.S.i

moddi3.s: moddi3.S.s

.PHONY : moddi3.s

# target to generate assembly for a file
moddi3.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/moddi3.S.s
.PHONY : moddi3.S.s

modsi3.obj: modsi3.S.obj

.PHONY : modsi3.obj

# target to build an object file
modsi3.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/modsi3.S.obj
.PHONY : modsi3.S.obj

modsi3.i: modsi3.S.i

.PHONY : modsi3.i

# target to preprocess a source file
modsi3.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/modsi3.S.i
.PHONY : modsi3.S.i

modsi3.s: modsi3.S.s

.PHONY : modsi3.s

# target to generate assembly for a file
modsi3.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/modsi3.S.s
.PHONY : modsi3.S.s

ulcmp.obj: ulcmp.S.obj

.PHONY : ulcmp.obj

# target to build an object file
ulcmp.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/ulcmp.S.obj
.PHONY : ulcmp.S.obj

ulcmp.i: ulcmp.S.i

.PHONY : ulcmp.i

# target to preprocess a source file
ulcmp.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/ulcmp.S.i
.PHONY : ulcmp.S.i

ulcmp.s: ulcmp.S.s

.PHONY : ulcmp.s

# target to generate assembly for a file
ulcmp.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/ulcmp.S.s
.PHONY : ulcmp.S.s

umoddi3.obj: umoddi3.S.obj

.PHONY : umoddi3.obj

# target to build an object file
umoddi3.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/umoddi3.S.obj
.PHONY : umoddi3.S.obj

umoddi3.i: umoddi3.S.i

.PHONY : umoddi3.i

# target to preprocess a source file
umoddi3.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/umoddi3.S.i
.PHONY : umoddi3.S.i

umoddi3.s: umoddi3.S.s

.PHONY : umoddi3.s

# target to generate assembly for a file
umoddi3.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/umoddi3.S.s
.PHONY : umoddi3.S.s

umodsi3.obj: umodsi3.S.obj

.PHONY : umodsi3.obj

# target to build an object file
umodsi3.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/umodsi3.S.obj
.PHONY : umodsi3.S.obj

umodsi3.i: umodsi3.S.i

.PHONY : umodsi3.i

# target to preprocess a source file
umodsi3.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/umodsi3.S.i
.PHONY : umodsi3.S.i

umodsi3.s: umodsi3.S.s

.PHONY : umodsi3.s

# target to generate assembly for a file
umodsi3.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/umodsi3.S.s
.PHONY : umodsi3.S.s

uread4.obj: uread4.S.obj

.PHONY : uread4.obj

# target to build an object file
uread4.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/uread4.S.obj
.PHONY : uread4.S.obj

uread4.i: uread4.S.i

.PHONY : uread4.i

# target to preprocess a source file
uread4.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/uread4.S.i
.PHONY : uread4.S.i

uread4.s: uread4.S.s

.PHONY : uread4.s

# target to generate assembly for a file
uread4.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/uread4.S.s
.PHONY : uread4.S.s

uread8.obj: uread8.S.obj

.PHONY : uread8.obj

# target to build an object file
uread8.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/uread8.S.obj
.PHONY : uread8.S.obj

uread8.i: uread8.S.i

.PHONY : uread8.i

# target to preprocess a source file
uread8.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/uread8.S.i
.PHONY : uread8.S.i

uread8.s: uread8.S.s

.PHONY : uread8.s

# target to generate assembly for a file
uread8.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/uread8.S.s
.PHONY : uread8.S.s

uwrite4.obj: uwrite4.S.obj

.PHONY : uwrite4.obj

# target to build an object file
uwrite4.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/uwrite4.S.obj
.PHONY : uwrite4.S.obj

uwrite4.i: uwrite4.S.i

.PHONY : uwrite4.i

# target to preprocess a source file
uwrite4.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/uwrite4.S.i
.PHONY : uwrite4.S.i

uwrite4.s: uwrite4.S.s

.PHONY : uwrite4.s

# target to generate assembly for a file
uwrite4.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/uwrite4.S.s
.PHONY : uwrite4.S.s

uwrite8.obj: uwrite8.S.obj

.PHONY : uwrite8.obj

# target to build an object file
uwrite8.S.obj:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/uwrite8.S.obj
.PHONY : uwrite8.S.obj

uwrite8.i: uwrite8.S.i

.PHONY : uwrite8.i

# target to preprocess a source file
uwrite8.S.i:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/uwrite8.S.i
.PHONY : uwrite8.S.i

uwrite8.s: uwrite8.S.s

.PHONY : uwrite8.s

# target to generate assembly for a file
uwrite8.S.s:
	cd /home/fla/projects/micromachine/sdk && $(MAKE) -f runtime-abi/CMakeFiles/libaeabi.dir/build.make runtime-abi/CMakeFiles/libaeabi.dir/uwrite8.S.s
.PHONY : uwrite8.S.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... libaeabi"
	@echo "... rebuild_cache"
	@echo "... crt.obj"
	@echo "... crt.i"
	@echo "... crt.s"
	@echo "... divdi3.obj"
	@echo "... divdi3.i"
	@echo "... divdi3.s"
	@echo "... idiv.obj"
	@echo "... idiv.i"
	@echo "... idiv.s"
	@echo "... idivmod.obj"
	@echo "... idivmod.i"
	@echo "... idivmod.s"
	@echo "... lasr.obj"
	@echo "... lasr.i"
	@echo "... lasr.s"
	@echo "... lcmp.obj"
	@echo "... lcmp.i"
	@echo "... lcmp.s"
	@echo "... ldivmod.obj"
	@echo "... ldivmod.i"
	@echo "... ldivmod.s"
	@echo "... llsl.obj"
	@echo "... llsl.i"
	@echo "... llsl.s"
	@echo "... llsr.obj"
	@echo "... llsr.i"
	@echo "... llsr.s"
	@echo "... lmul.obj"
	@echo "... lmul.i"
	@echo "... lmul.s"
	@echo "... memmove.obj"
	@echo "... memmove.i"
	@echo "... memmove.s"
	@echo "... memset.obj"
	@echo "... memset.i"
	@echo "... memset.s"
	@echo "... moddi3.obj"
	@echo "... moddi3.i"
	@echo "... moddi3.s"
	@echo "... modsi3.obj"
	@echo "... modsi3.i"
	@echo "... modsi3.s"
	@echo "... ulcmp.obj"
	@echo "... ulcmp.i"
	@echo "... ulcmp.s"
	@echo "... umoddi3.obj"
	@echo "... umoddi3.i"
	@echo "... umoddi3.s"
	@echo "... umodsi3.obj"
	@echo "... umodsi3.i"
	@echo "... umodsi3.s"
	@echo "... uread4.obj"
	@echo "... uread4.i"
	@echo "... uread4.s"
	@echo "... uread8.obj"
	@echo "... uread8.i"
	@echo "... uread8.s"
	@echo "... uwrite4.obj"
	@echo "... uwrite4.i"
	@echo "... uwrite4.s"
	@echo "... uwrite8.obj"
	@echo "... uwrite8.i"
	@echo "... uwrite8.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/fla/projects/micromachine/sdk && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

